language: php
php:
  - 7.4
  - 8.0

install:
  - phpenv rehash
  - composer self-update
  - composer require --dev php-coveralls/php-coveralls
  - composer install

script:
  - mkdir -p build/logs
  - XDEBUG_MODE=coverage phpunit ./tests --bootstrap="vendor/autoload.php" --coverage-clover ./build/logs/clover.xml --whitelist src

after_script:
  - travis_retry php vendor/bin/php-coveralls